version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  node-express:
    image: wicemcharef/ node:18-buster
    container_name: node-express
    working_dir: /usr/src/app
    volumes:
      - ./node-express:/usr/src/app
    command: sh -c "npm init -y && npm install && npm start"
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      PROJECT_DATA_PATH: /path/to/project
    depends_on:
      - postgres

  nextjs:
    image: wicemcharef/node:18-buster
    container_name: nextjs
    working_dir: /usr/src/app
    volumes:
      - ./nextjs:/usr/src/app
    command: sh -c "npm init -y && npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - node-express

volumes:
  postgres-data:
